In [8]:
import numpy as np

np.random.rand()
np.random.sample()
np.random.uniform(-10, 5, size=(2, 3))


array([[ 1.91598696, -1.6288373 , -8.02822187],
       [-7.88832281, -7.8308251 , -4.39168842]])

In [14]:
import numpy as np

arr = np.random.randint(1, 4, size=(2,3))
print(arr)

[[1 2 3]
 [3 1 2]]


In [18]:
import numpy as np
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=3, replace=True)
print(choice)

['Kate' 'Kate' 'John']


In [34]:
import numpy as np
np.random.seed(2021)

#В simple сохраните случайное число в диапазоне от 0 до 1
simple = np.random.rand()
print(simple)
print('')

#Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их в переменную randoms
#randoms = np.random.uniform(-150, 2021, size=120)
#print(randoms)
print("")

#Получите массив из случайных целых чисел от 1 до 100 (включительно) из 3 строк и 2 столбцов.
#Сохраните результат в table
table = np.random.randint(1, 101, size=(3, 2))
print(table)
print('')

#B переменную even сохраните четные числа от 2 до 16 (включительно)
even = np.arange(2, 17, 2)
print(even)
print('')

#Скопируйте even в переменную mix. Перемешайте числа в mix так, чтобы массив изменился
mix = np.random.permutation(even)
print(mix)
print("")

#Получите из even 3 числа без повторений. Сохраните их в переменную select
select = np.random.choice(even,size=3, replace=False)
print(select)
print('')

#Получите переменную triplet, которая должна содержать перемешанные значения из массива select (сам select измениться не должен)
triplet = np.random.permutation(select)
print(triplet)


0.6059782788074047


[[58  1]
 [95 87]
 [45 63]]

[ 2  4  6  8 10 12 14 16]

[ 4 16  6 10  2 14 12  8]

[ 8  2 10]

[10  8  2]


In [43]:
#Напишите функцию get_chess(a), которая принимает на вход длину стороны квадрата a и 
#возвращает двумерный массив формы (a, a), заполненный 0 и 1 в шахматном порядке.
#В левом верхнем углу всегда должен быть ноль.
#Примечание. воспользуйтесь функцией np.zeros, а затем с помощью срезов без циклов задайте необходимым элементам значение 1.
# В Python для получения каждого второго элемента используется срез [::2]. 
# Подумайте, как грамотно применить этот принцип к двумерному массиву.

import numpy as np

def get_chess(a):
    arr = np.zeros((a,a))
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr


get_chess(4)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [44]:

#Вы разрабатываете приложение для прослушивания музыки.
# Конечно же, там будет доступна функция перемешивания плейлиста. 
# Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию.
# Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.
# Для этого напишите функцию shuffle_seed(array), которая принимает на вход массив из чисел, 
# генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж:
# перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.
import numpy as np
def shuffle_seed(array):
    seed = np.random.randint(2**32)
    np.random.seed(seed)
    result = np.random.permutation(array)
    return result, seed
array = [1, 2, 3, 4, 5]
shuffle_seed(array)

(array([4, 2, 1, 5, 3]), 2471788226)

In [45]:
#Напишите функцию min_max_dist(*vectors), 
#которая принимает на вход неограниченное число векторов через запятую.
#Гарантируется, что все векторы, которые передаются, одинаковой длины.
#Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.
import numpy as np
def min_max_dist(*vectors):
    dists = list()
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            dists.append(np.linalg.norm(vectors[i] - vectors[j]))
    return (min(dists), max(dists))

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)        

(5.196152422706632, 10.392304845413264)

In [4]:
#Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. 
# Гарантируется, что все векторы, которые передаются, одинаковой длины.
# Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

import numpy as np
def any_normal(*vectors):
    
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            if np.dot(vectors[i], vectors[j]) == 0:
                return True
    return False         

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))


True


In [10]:
#Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). 
#Это поля для игры в лото.
# Tрёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).
# Функция возвращает полученный массив.

import numpy as np
def get_loto(num):
    arr = np.random.randint(1, 101, size=(num, 5, 5))
    return arr

get_loto(3)


array([[[77, 14, 36, 13, 12],
        [90, 83, 54, 21, 27],
        [30, 57, 85, 81, 66],
        [60, 68, 25, 67, 55],
        [30, 29, 85, 35,  7]],

       [[67, 43,  4, 63, 97],
        [21, 64, 98, 85, 74],
        [41, 38, 26, 66, 34],
        [26, 20, 24, 85, 40],
        [98, 73,  4, 91, 57]],

       [[12, 87, 56, 29, 39],
        [41, 46,  6, 52, 70],
        [37, 85, 59, 38, 69],
        [98, 73, 31, 39, 51],
        [77, 81,  8, 65, 28]]])

In [14]:
#Напишите функцию get_unique_loto(num). 
# Она так же, как и функция в задании 10.10, генерирует num полей для игры в лото, 
# однако теперь на каждом поле 5х5 числа не могут повторяться.
# Функция также должна возвращать массив формы num x 5 x 5.


import numpy as np

def get_unique_loto(num):
    sample = np.arange(1, 101)
    res = list()
    for i in range(num):
        res.append(np.random.choice(sample, replace=False, size=(5,5)))
    res =np.array(res)
    return res

get_unique_loto(3)    

array([[[ 24,  67,  47,  80,  27],
        [ 41,  62,   4,  90,  59],
        [ 43,   1,  15,  56,  53],
        [ 84,  10,  94,  66,  65],
        [ 48,  68,  96,  34,  44]],

       [[ 34,  48, 100,  77,  20],
        [ 51,   5,  10,  91,  17],
        [ 87,  90,  60,  44,   9],
        [ 98,  84,  71,  12,  52],
        [ 53,  21,  37,  46,  43]],

       [[ 96,  45,  68,  33,   5],
        [ 56,  74,  15,  89,   7],
        [ 14,  17,   6,  75,  99],
        [ 77,  29,  93,  30,  70],
        [ 94,  44,  84,  57,  88]]])