In [1]:
import numpy as np

zeros_3d = np.zeros((5, 4, 3), dtype=np.float32)
print(zeros_3d) 

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [12]:
import numpy as nd
arr = np.array([
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
arr[2][1]=10
arr
arr.dtype

dtype('int64')

In [21]:
import numpy as np

arr, step = np.linspace(-6, 21, 60,endpoint=False, retstep=True)
print(step)
arr

0.45


array([-6.  , -5.55, -5.1 , -4.65, -4.2 , -3.75, -3.3 , -2.85, -2.4 ,
       -1.95, -1.5 , -1.05, -0.6 , -0.15,  0.3 ,  0.75,  1.2 ,  1.65,
        2.1 ,  2.55,  3.  ,  3.45,  3.9 ,  4.35,  4.8 ,  5.25,  5.7 ,
        6.15,  6.6 ,  7.05,  7.5 ,  7.95,  8.4 ,  8.85,  9.3 ,  9.75,
       10.2 , 10.65, 11.1 , 11.55, 12.  , 12.45, 12.9 , 13.35, 13.8 ,
       14.25, 14.7 , 15.15, 15.6 , 16.05, 16.5 , 16.95, 17.4 , 17.85,
       18.3 , 18.75, 19.2 , 19.65, 20.1 , 20.55])

In [11]:
import numpy as np

arr = np.arange(8)
print(arr)
arr.shape = (2, 4)
print(arr)
print('')

#сохранение старого массива и создание нового
arr_new = arr.reshape((4,2))
print(arr_new)
print('')

arr_1 = np.arange(10)
arr_new_2 = arr_1.reshape((2, 5), order='F') #заполнение массива по столбцам
print(arr_new_2)


[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[[0 2 4 6 8]
 [1 3 5 7 9]]


In [13]:
import numpy as np
arr = np.arange(8)
arr.shape = (2, 4)
print(arr)
print('')
arr_new = arr.transpose() #функция меняет строки и столбцы местами
print(arr_new)
print(arr_new[::-1])

[[0 1 2 3]
 [4 5 6 7]]

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
[[3 7]
 [2 6]
 [1 5]
 [0 4]]


In [33]:
mystery = np.array([
        [-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

mystery.shape
elem_5_3 = mystery[4,  2]
print(elem_5_3)
last = mystery[5, 6]
print(last)
line_4 = mystery[3]
print(line_4)
col_2 = mystery[::,-2]
print(col_2)
rev = reversed(mystery[::, -1])



30305
-32037
[13240  7994 32592 20149 13754 11795  -564]
[-17182  15790  25397  11795  12578    -47]
