In [16]:
import numpy as np

vec1 = np.array([1, 2, 3, 4])
vec2 = np.array([1, 2, 3, 6])

#Operation vectors
print(vec1 + vec2)  #sum
print(vec2 - vec2)
print(vec1 ** vec2)
print(vec1 * 10)
print(vec1 + 10)
print(vec1 <= 1)

#Вычисление длины вектора и расстояния м/у векторами
print('Вычисление длины вектора')
length = np.linalg.norm(vec1)
print(length)
print('Вычисление расстояния м/у векторами')
distance = np.linalg.norm(vec1 - vec2)
print(distance)
print('')

#Скалярное произведение 2-х векторов
print('скалярное произведение')
print('')
vec3 = np.arange(1, 6)
vec4 = np.linspace(20, 30, 5)
scalar = np.dot(vec3, vec4)
print(scalar)


[ 2  4  6 10]
[0 0 0 0]
[   1    4   27 4096]
[10 20 30 40]
[11 12 13 14]
[ True False False False]
Вычисление длины вектора
5.477225575051661
Вычисление расстояния м/у векторами
2.0

скалярное произведение

400.0
